spring:
  profiles:
    active: koTime
koTime:
  log:
    enable: false  # 是否开启控制输出，非必填，默认false
    language: chinese # 控制台输出语言（english/chinese）非必填，默认chinese
  ime:
    threshold: 800.0 # 时间阈值，用于前端展示，大于阈值显示红色，小于阈值显示绿色，非必填，默认800
  pointcut: execution(* com.example.firewall.controller.*.*(..))